# Generated by Django 4.1.7 on 2023-04-05 21:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('publication', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='effect',
            old_name='post',
            new_name='post_media',
        ),
    ]
