# Generated by Django 4.1.7 on 2023-04-15 06:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('messaging', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='message',
            name='last_update_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
