# Generated by Django 4.1.7 on 2023-03-28 15:39

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='BroadcastEmail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('broadcast', models.BooleanField(default=False, verbose_name='message difusé')),
                ('subject', models.CharField(max_length=1024, verbose_name='sujet')),
                ('message', models.TextField(max_length=128000, verbose_name='contenu du mail ')),
                ('sending_date', models.DateTimeField(default=django.utils.timezone.now, verbose_name="date d'envoi")),
            ],
            options={
                'verbose_name': 'Diffusion de mail',
            },
        ),
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('readed', models.BooleanField(default=False, verbose_name='lu')),
                ('name', models.CharField(default='inconu', max_length=128, verbose_name="nom de l'éxpediteur")),
                ('email', models.EmailField(max_length=254, verbose_name='adresse mail')),
                ('subject', models.CharField(blank=True, max_length=1024, verbose_name='sujet')),
                ('content', models.TextField(max_length=128000, verbose_name='contenu du message')),
                ('sending_date', models.DateTimeField(default=django.utils.timezone.now, verbose_name="date d'envoi")),
                ('author', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='expéditeur')),
            ],
            options={
                'verbose_name': 'Message',
            },
        ),
    ]
